start:  expression+
expression: atom | "(" expression+ ")" 

atom: WORD+ | NUMBER+ | SYMBOL

SYMBOL:  "+" | "*" | "-" | "/" | "%"
WORD:  LETTER+
NUMBER: INT+
comment_mark: ";"
%import common.LETTER
%import common.INT
%import common.WS_INLINE
%import common.NEWLINE
%ignore WS_INLINE
%ignore NEWLINE